<?php
     $which_page = "workshops";
     include('frags/common_header.php');
?>


<table>
<tr><td colspan="3" align="center"><h2>ICCV 2013 Accepted Workshops</h2><br/><br/>Organizers, please contact <a href="http://www.google.com/recaptcha/mailhide/d?k=01dWLb3jj9XNr5b6NtY-9tKw==&c=fku1_6PuLNW2yDA61h1j4MH_nGDhQEodkkZE4vqSlAE=" target="_blank">Ryan Farrell</a> with needed updates. </td></tr>
<tr><td colspan="3" align="center"><br/><br/>Submit camera-ready papers <a href="http://www.ieeeconfpublishing.org/cpir/authorKit.asp?Facility=CPS_Dec&ERoom=ICCVW+2013" target="_blank">here</a>.</td></tr>
<tr><td colspan="3">
<table cellspacing="0" cellpadding="2" width="100%">
<tr><td width="10%" align="center"><u><b>Date</b></u></td><td width="*"><u><b>Workshop Title / Organizers</b></u></td><td width="10%"><u><b>Submission</b></u></td></tr>


<tr valign="top" bgcolor="#DDDDDD"><td align="center">12/02/13</br><i>(AM only)</i></td><td><b><a href="http://www.centrale-ponts.fr/personnel/komodakis/GraphM-SceneU-iccv2013" target="_blank">Graphical models for scene understanding: challenges and perspectives</a></b><br><i>Organizers: Nikos&nbsp;Komodakis, Christoph&nbsp;Schnoerr, Carsten&nbsp;Rother, Raquel&nbsp;Urtasun, Bogdan&nbsp;Savchynskyy</i></td><td align="center">09/07/13</td></tr>
<tr valign="top" bgcolor="#FFFFFF"><td align="center">12/02/13</td><td><b><a href="http://www.vision.ee.ethz.ch/CDC4CV/" target="_blank">3rd Workshop on Consumer Depth Cameras for Computer Vision (CDC4CV)</a></b><br><i>Organizers: Andrea&nbsp;Fossati, Juergen&nbsp;Gall, Helmut&nbsp;Grabner, Miles&nbsp;Hansard</i></td><td align="center">09/11/13</td></tr>
<tr valign="top" bgcolor="#DDDDDD"><td align="center">12/02/13</td><td><b><a href="http://www.votchallenge.net/" target="_blank">IEEE Workshop on the VOT2013 Visual Object Tracking Challenge</a></b><br><i>Organizers: Roman&nbsp;Pflugfelder, Matej&nbsp;Kristan, Ales&nbsp;Leonardis, Jiri&nbsp;Matas, Fatih&nbsp;Porikli</i></td><td align="center">09/14/13</td></tr>
<tr valign="top" bgcolor="#FFFFFF"><td align="center">12/02/13</td><td><b><a href="http://ttic.uchicago.edu/~rurtasun/rmrc/index.php" target="_blank">Reconstruction Meets Recognition Challenge</a></b><br><i>Organizers: Raquel&nbsp;Urtasun, Rob&nbsp;Fergus, Derek&nbsp;Hoiem, Antonio&nbsp;Torralba, Andreas&nbsp;Geiger, Philip&nbsp;Lenz, Nathan&nbsp;Silberman, Jianxiong&nbsp;Xiao, Sanja&nbsp;Fidler</i></td><td align="center">TBD</td></tr>
<tr valign="top" bgcolor="#DDDDDD"><td align="center">12/02/13</td><td><b><a href="http://www.visionbasedsportsanalytics.net/" target="_blank">Vision-Based Sports Analytics</a></b><br><i>Organizers: Patrick&nbsp;Lucey, Peter&nbsp;Carr, Iain&nbsp;Matthews, Stuart&nbsp;Morgan</i></td><td align="center"></td></tr>
<tr valign="top" bgcolor="#FFFFFF"><td align="center">12/02/13</td><td><b><a href="http://australianbioinformatics.net/cvab-2013" target="_blank">Workshop on Computer Vision for Accelerated Bioscience</a></b><br><i>Organizers: David&nbsp;Lovell, Matt&nbsp;Adcock, Shahram&nbsp;Izadi, Chuong&nbsp;Nguyen, Hongdong&nbsp;Li</i></td><td align="center">09/25/13</td></tr>
<tr valign="top" bgcolor="#DDDDDD"><td align="center">12/02/13</td><td><b><a href="http://www.cs.cmu.edu/~CVAD2013" target="_blank">Workshop on Computer Vision for Autonomous Driving</a></b><br><i>Organizers: Bart&nbsp;Nabbe, Yaser&nbsp;Sheikh, Uwe&nbsp;Franke, Martial&nbsp;Hebert, Fernando&nbsp;De la Torre, Raquel&nbsp;Urtasun</i></td><td align="center">09/10/13</td></tr>
<tr valign="top" bgcolor="#FFFFFF"><td align="center">12/02/13</br><i>(PM only)</i></td><td><b><a href="http://cs.adelaide.edu.au/~chhshen/iccv2013_workshop/" target="_blank">Inference for probabilistic graphical models (PGMs)</a></b><br><i>Organizers: Qinfeng (Javen)&nbsp;Shi, Chunhua&nbsp;Shen , Stephen&nbsp;Gould , Jason L.&nbsp;Williams , Tiberio&nbsp;Caetano</i></td><td align="center">09/17/13</td></tr>
<tr valign="top" bgcolor="#DDDDDD"><td align="center">12/07/13</td><td><b><a href="http://campar.in.tum.de/FourDMod13/WebHome" target="_blank">2nd International Workshop on Dynamic Shape Capture and Analysis (4DMOD)</a></b><br><i>Organizers: Slobodan&nbsp;Ilic, Edmond&nbsp;Boyer, Adrian&nbsp;Hilton</i></td><td align="center">09/07/13</td></tr>
<tr valign="top" bgcolor="#FFFFFF"><td align="center">12/07/13</td><td><b><a href="http://www.ntu.edu.sg/home/jsyuan/lsvsm13/" target="_blank">2nd International Workshop on Large-Scale Video Search and Mining (LSVSM)</a></b><br><i>Organizers: Junsong&nbsp;Yuan, John&nbsp;Smith, Shih-Fu&nbsp;Chang</i></td><td align="center">09/07/13</td></tr>
<tr valign="top" bgcolor="#DDDDDD"><td align="center">12/07/13</td><td><b><a href="http://ibug.doc.ic.ac.uk/resources/300-W/" target="_blank">300 Faces in-the-Wild Challenge (300-W)</a></b><br><i>Organizers: Maja&nbsp;Pantic, Georgios&nbsp;Tzimiropoulos, Stefanos&nbsp;Zafeiriou</i></td><td align="center">09/07/13</td></tr>
<tr valign="top" bgcolor="#FFFFFF"><td align="center">12/07/13</td><td><b><a href="http://www.image-net.org/challenges/LSVRC/2013/iccv2013.php" target="_blank">ImageNet Large Scale Visual Recognition Challenge 2013 (ILSVRC2013) Workshop</a></b><br><i>Organizers: Olga&nbsp;Russakovsky, Jonathan&nbsp;Krause, Jia&nbsp;Deng, Alex&nbsp;Berg, Fei-Fei&nbsp;Li</i></td><td align="center">11/15/13</td></tr>
<tr valign="top" bgcolor="#DDDDDD"><td align="center">12/07/13</td><td><b><a href="http://www.lsviscom.org/" target="_blank">Large Scale Visual Commerce (LSVisCom)</a></b><br><i>Organizers: Anurag&nbsp;Bhardwaj, Robinson&nbsp;Piramuthu, Serge&nbsp;J. Belongie, Tsuhan&nbsp;Chen</i></td><td align="center">09/09/13</td></tr>
<tr valign="top" bgcolor="#FFFFFF"><td align="center">12/07/13</td><td><b><a href="http://crcv.ucf.edu/ICCV13-Action-Workshop/" target="_blank">THUMOS: The First International Workshop on Action Recognition with a Large Number of Classes</a></b><br><i>Organizers: Ivan&nbsp;Laptev, Massimo&nbsp;Piccardi, Mubarak&nbsp;Shah, Rahul&nbsp;Sukthankar, Yu-Gang&nbsp;Jiang, Jingen&nbsp;Liu, Amir Roshan&nbsp;Zamir</i></td><td align="center">11/07/13</td></tr>
<tr valign="top" bgcolor="#DDDDDD"><td align="center">12/07/13</td><td><b><a href="http://visda2013.seas.harvard.edu " target="_blank">VisDA: 1st International Workshop on Visual Domain Adaptation</a></b><br><i>Organizers: Brian&nbsp;Kulis, Ruonan&nbsp;Li, Kate&nbsp;Saenko, Fei&nbsp;Sha</i></td><td align="center">09/07/13</td></tr>
<tr valign="top" bgcolor="#FFFFFF"><td align="center">12/07/13</td><td><b><a href="https://sites.google.com/site/wwcv2013/" target="_blank">Workshop on Wearable Computer Vision Systems (WCVS)</a></b><br><i>Organizers: Ana C.&nbsp;Murillo, Javier&nbsp;Civera, Mohammad&nbsp;Moghimi, Serge&nbsp;Belongie</i></td><td align="center">09/06/13</td></tr>
<tr valign="top" bgcolor="#DDDDDD"><td align="center">12/08/13</br><i>(AM only)</i></td><td><b><a href="http://web.ornl.gov/~czx/open/cvcp13.html" target="_blank">IEEE Workshop on Computer Vision for Converging Perspectives</a></b><br><i>Organizers: Anil&nbsp;Cheriyadat, Shawn&nbsp;Newsam, Mei&nbsp;Han</i></td><td align="center">09/01/13</td></tr>
<tr valign="top" bgcolor="#FFFFFF"><td align="center">12/08/13</td><td><b><a href="http://haci2013.umiacs.umd.edu/" target="_blank">1st Workshop on Understanding Human Activities: Context and Interactions (HACI 2013)</a></b><br><i>Organizers: Sameh&nbsp;Khamis, Mohamed&nbsp;R. Amer, Wongun&nbsp;Choi, Tian&nbsp;Lan</i></td><td align="center">09/13/13</td></tr>
<tr valign="top" bgcolor="#DDDDDD"><td align="center">12/08/13</td><td><b><a href="http://homes.cs.washington.edu/~sunmin/3dRR13/3dRR13.html" target="_blank">4th Workshop on 3D Representation and Recognition (3dRR-13)</a></b><br><i>Organizers: Min&nbsp;Sun, Michael&nbsp;Stark, Silvio&nbsp;Savarese</i></td><td align="center">09/05/13</td></tr>
<tr valign="top" bgcolor="#FFFFFF"><td align="center">12/08/13</td><td><b><a href="http://www.cvc.uab.es/adas/cvvt2013/" target="_blank">4th Workshop on Computer Vision in Vehicle Technology: From Earth to Mars</a></b><br><i>Organizers: David&nbsp;Ger&oacute;nimo, Atsushi&nbsp;Imiya, Antonio M.&nbsp;L&oacute;pez, Theo&nbsp;Gevers, Urbano&nbsp;Nunes, Dariu M.&nbsp;Gavrila, Tomas&nbsp;Pajdla, Steven&nbsp;Beauchemin</i></td><td align="center">09/05/13</td></tr>
<tr valign="top" bgcolor="#DDDDDD"><td align="center">12/08/13</td><td><b><a href="http://www.multimediauts.org/BigData3DCV/" target="_blank">Big Data in 3D Computer Vision Workshop</a></b><br><i>Organizers: Jian&nbsp;Zhang, Mohammed&nbsp;Bennamoun, Dan&nbsp;Schonfeld, Zhengyou&nbsp;Zhang, Fatih&nbsp;Porikli, Dong&nbsp;Xu, Hongdong&nbsp;Li, Qiang&nbsp;Wu</i></td><td align="center">09/07/13</td></tr>
<tr valign="top" bgcolor="#FFFFFF"><td align="center">12/08/13</td><td><b><a href="http://www.cbi.gatech.edu/CBSICCV2013/" target="_blank">Decoding Subtle Cues from Social Interactions</a></b><br><i>Organizers: David A.&nbsp;Forsyth, Yin&nbsp;Li, James M.&nbsp;Rehg</i></td><td align="center">09/30/13</td></tr>
<tr valign="top" bgcolor="#DDDDDD"><td align="center">12/08/13</td><td><b><a href="http://www.computing.dundee.ac.uk/staff/jgzhang/VECTaR2013.htm  " target="_blank">The 5th International Workshop on Video Event Categorization, Tagging and Retrieval (VECTaR2013)</a></b><br><i>Organizers: Tieniu&nbsp;Tan, Thomas&nbsp;S. Huang, Liang&nbsp;Wang, Ling&nbsp;Shao, Jianguo&nbsp;Zhang, Yun&nbsp;Fu</i></td><td align="center">09/07/13</td></tr>
<tr valign="top" bgcolor="#FFFFFF"><td align="center">12/08/13</td><td><b><a href="http://marine.acfr.usyd.edu.au/iccv13uv/" target="_blank">Underwater Vision Workshop</a></b><br><i>Organizers: Stefan&nbsp;Williams, Navid&nbsp;Nourani-Vatani, Ariell&nbsp;Friedman, Daniel&nbsp;Steinberg, Oscar&nbsp;Pizarro</i></td><td align="center">09/07/13</td></tr>
<tr valign="top" bgcolor="#DDDDDD"><td align="center">12/08/13</br><i>(PM only)</i></td><td><b><a href="http://www.wcpcv.com/2013/" target="_blank">Color and Photometry in Computer Vision</a></b><br><i>Organizers: Theo&nbsp;Gevers, Joost&nbsp;van de Weijer, Todd&nbsp;Zickler, Jose&nbsp;Alvarez</i></td><td align="center">09/07/13</td></tr>



<?php
    include('frags/common_footer.php');    
?>


