<?php
    $which_page = "extended_abstracts";
    include('common_header.php');
?>

<center>
<table>
<tbody><tr><td colspan="3" align="center"><span class="cvprparagraphheader">INSTRUCTIONS FOR FORMATTING AND SUBMITTING EXTENDED ABSTRACTS FOR CVPR 2015</span><br />
</td></tr>
<tr><td colspan="3">

<p><b>Note: in addition to the instructions below, all authors need to
<a href="camera_ready_instructions.php">submit the final camera-ready
paper</a>, also due at April 10, 2015 at 11:59pm Pacific Time.</b></p>

<p>Authors of each paper accepted to CVPR 2015 (oral and poster) are
required to submit a one page extended abstract that highlights and
summarizes your CVPR 2015 paper.  These extended abstracts will be
collated into larger documents that provide an overview of each day of
the conference.  Please read these instructions carefully to ensure
that your extended abstract is formatted and submitted correctly.</p>

<p>The deadline for submitting your extended abstract is April 10,
2015 at 11:59pm Pacific Time.  This is the same deadline as the full
camera-ready paper.</p>

<p><b>Format:</b> Templates for the extended abstract are available in
LaTex and Word formats at the CVPR 2015 web site - <a
href="http://www.pamitc.org/cvpr15/files/CVPR2015_extended_abstracts.zip">http://www.pamitc.org/cvpr15/files/CVPR2015_extended_abstracts.zip</a></p>

</p>Your extended abstract should ideally give the elevator pitch of
your paper, briefly highlighting the main new idea and the key
results, perhaps with an essential figure(s).  It should help
conference attendees get the gist of the paper before they attend your
talk/poster, as well as other readers browsing the CVPR proceedings
after the conference.  Please see the example included in the .zip
file above for ideas.</p>

<p>The extended abstract is strictly limited to one page.  This one
page limit includes all figures, references, acknowledgements, etc.
The extended abstract format must follow the templates provided in
terms of fonts, font sizes, margins, etc.</p>

<p>There is a strict size limit of 5 MB (5,242,880 bytes) for the PDF
file of your one-page extended abstract. If your paper is larger than
this, you are probably using very large images in your figures. As a
rule, your images will look fine at 600 pixels per inch and you should
down-sample the images used in your figures accordingly.</p>

<p>To ensure that the PDF file has the greatest portability across
devices and operating systems, we suggest that you use IEEE eXpress to
validate your PDF file.  This is only a suggestion and is NOT required
to submit your extended abstract.  The advantage of using IEEE eXpress
is that it will ensure that your file does not use non-embeddable
fonts in your PDF file.  IEEE eXpress can also generate a validated
PDF file from your Word or LaTex files.  If you wish to validate your
PDF file prior to submitting it, follow the instructions in step 1 of
the camera-ready submission instructions you received (and which are
available on the CVPR 2015 webpage at <a
href="http://www.pamitc.org/cvpr15/camera_ready_instructions.php">http://www.pamitc.org/cvpr15/camera_ready_instructions.php</a>).</p>

<p><b>Note:</b> The PDF file generated by the provided LaTex template
passes IEEE eXpress validation with a caution about the CVF link at
the bottom.  Since the extended abstracts will not be archived on IEEE
Xplore, you can ignore this caution.  The Microsoft Word template also
passes the PDF validation if you submit the Word file directly to IEEE
eXpress and let it perform the PDF conversion.</p>

<p><b>Submission:</b> Your one page extended abstract is to be
submitted as a single PDF file using the "Presentation" page in CMT,
as detailed in the steps below.  Your extended abstract must be
submitted as a PDF file.  (Note that although the "Presentation"
submission page allows for other formats, any file format other than
PDF will be discarded).  Your extended abstract will not be edited for
content, but it will be combined with other extended abstracts into a
single PDF file containing all the extended abstracts for a given day
of the conference.</p>

<ol type="a" class="body_ul">

    <li>To submit your extended abstract PDF file, login to the CMT
    paper collection site - <a
    href="https://cmt.research.microsoft.com/CVPR2015/">https://cmt.research.microsoft.com/CVPR2015/</a></li>

    <li>In the CMT "Author Console", your accepted paper(s) will
    appear in the "Camera-Ready | Presentations" column.  Click on the
    "Edit" link beneath the "Presentation" heading (next to your paper
    title).  DO NOT click on the "Edit" link next to the
    "Camera-Ready" heading or on the "Submit IEEE Copyright
    Form" - these links are for submitting your full, camera-ready paper
    as described in the camera-ready instructions.</li>

    <li>Similar to the full, camera-ready submission, the name of your
    extended abstract must be of the form XXXX_ext.pdf where XXXX is
    the four-digit paper ID (zero-padded if necessary). For example,
    if your paper ID is 24, the filename must be 0024_ext.pdf.</li>

    <li>Use the "Browse" and "Upload" buttons on the "Presentation
    Details" page to find and upload your one-page PDF file of your
    extended abstract.</li>

    <li>You do not need to enter any "Presenters" for your extended
    abstract.</li>

   <li>Again, the deadline for submitting your one page extended
   abstract is April 10, 2015 at 11:59pm Pacific Time.</li>

</ol>

</td></tr>
</tbody></table>


</center>

	<?php
	include('common_footer.php');
	?>
